export class commercemodel {
public nit                      : any;
public name                     : any;
public phone                    : any;
public email                    : any;
public redes_sociales           : any;
public id_class_commerce	    : any;
public main_activity		    : any;
public address				    : any;
public country				    : any;
public department			    : any;
public city					    : any;
public neighborhood			    : any;
public apple				    : any;
public description			    : any;
public id_service			    : any;
public id_state_commerce	    : any;
public start_date			    : any;
public end_date				    : any;
public lat	        		    : any;
public long 				    : any;
public id_type_comunication	    : any;
public id_type_content_commerce : any;
}